export const FETCH_LOOKUP='FETCH_LOOKUP';
export const FETCH_RATE_CUR='FETCH_RATE_CUR';
export const FETCH_RATE_ALL='FETCH_RATE_ALL';
export const FETCH_MOVIE_NEWS='FETCH_MOVIE_NEWS';
export const FETCH_MOVIE_DETAIL='FETCH_MOVIE_DETAIL';